### ISSUE TITLE
Tweak examples

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/duckplyr-archive#1]
Unlike [duckdblabs/duckplyr@`b17e9bb` (#35)](https://github.com/duckdblabs/duckplyr/pull/35/commits/b17e9bb2dcb297bcafb48f6d1510fbf9264129f2), we don't need a full-fledged implementation in the package. We can create dummy methods in the examples directly.

I can start with an example.

CC @maelle.

**Comment by maelle** [comment]
What happened to `rel_from_df()`? It looked useful in the current examples.

**Comment by krlmlr** [comment]
Closed in 354532dbce3593525a7c2a61de769d9428bcb4ff.
