### ISSUE TITLE
Add pkgdown page

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/duckplyr-archive#3]
for preview of the docs.

**Comment by maelle** [comment]
@krlmlr 

- Could you please run `usethis::use_pkgdown_github_pages()`? One needs admin access (at least I think that's what it failed for me).

- What exactly do you mean by preview? 
    - Should I then tweak the GHA workflow so it deploys any branch whose name starts with docs, which is the case in many cynkra repos?
    - Or should the GHA workflow stay as is, which means in PRs the website is built but deployed nowhere (not a preview :sweat_smile:)?
    - Or should there be a Netlify preview for PRs (pro: not overwriting the development website with contents from branches)?

**Comment by krlmlr** [comment]
Done, thanks!

**Comment by maelle** [comment]
@krlmlr so this gives you no preview, is that good so?

**Comment by krlmlr** [comment]
https://krlmlr.github.io/duckplyr/ is the preview, that's fine.
