### ISSUE TITLE
Check whether we can unquote dplyr in Title

### ISSUE THREAD

**Issue by maelle** [krlmlr/duckplyr-archive#6]
Probably not prioritary (I think the current situation is acceptable). 

I am a bit worried the usual "hack" for unquoting would not remove the Note I just fixed:

> The Title field should be in title case. Current version is:
  ‘Relational API for alternative dplyr implementations’
  In title case that is:
  ‘Relational API for Alternative Dplyr Implementations’

Since we surely don't want to capitalize dplyr. :scream_cat:

**Comment by krlmlr** [comment]
"Alternative Implementations of the Grammar of Data Manipulations" ?

Maybe API is also risky, perhaps "Generics for ..." ?
