### ISSUE TITLE
Fix pak url in README.md manually right before submission

### ISSUE THREAD

**Issue by maelle** [krlmlr/duckplyr-archive#7]
or .Rbuildignore README.md? This might be preferable.

The URL is wrong because we use downlit autolinking + https://github.com/r-lib/pak/pull/493 hasn't been released yet. (https://pak.r-lib.org/pkgdown.yml has the http link; https://pak.r-lib.org/dev/pkgdown.yml doesn't but won't become the main website until the next CRAN release of pak).

**Comment by krlmlr** [comment]
We can tweak the `.md` just before release. No need to act now.
